# Test Results (FE + RS)
# ============================= test session starts =============================
# collecting ... collected 34 items
# 
# tests/test_feature_engineering.py::TestCoreFormulas::test_income_stability_index FAILED [  2%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_debt_to_income FAILED [  5%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_savings_rate FAILED [  8%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_emi_cushion_index FAILED [ 11%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_expenditure_volatility FAILED [ 14%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_salary_delay_trend FAILED [ 17%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_cash_deposit_pattern_score FAILED [ 20%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_discretionary_spending_ratio FAILED [ 23%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_payment_timing_consistency FAILED [ 26%]
# tests/test_feature_engineering.py::TestCoreFormulas::test_account_balance_trajectory FAILED [ 29%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_subscription_cascade FAILED [ 32%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_digital_wallet_velocity FAILED [ 35%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_merchant_downgrade PASSED [ 38%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_healthcare_spike FAILED [ 41%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_employer_contagion FAILED [ 44%]
# tests/test_feature_engineering.py::TestAdvancedBehavioral::test_gig_income_variance FAILED [ 47%]
# tests/test_feature_engineering.py::TestFullPipeline::test_run_produces_features FAILED [ 50%]
# tests/test_feature_engineering.py::TestFullPipeline::test_no_all_nan_columns FAILED [ 52%]
# tests/test_risk_scorer.py::TestRiskBandClassification::test_safe_band FAILED [ 55%]
# tests/test_risk_scorer.py::TestRiskBandClassification::test_low_risk_band FAILED [ 58%]
# tests/test_risk_scorer.py::TestRiskBandClassification::test_moderate_band FAILED [ 61%]
# tests/test_risk_scorer.py::TestRiskBandClassification::test_high_risk_band FAILED [ 64%]
# tests/test_risk_scorer.py::TestRiskBandClassification::test_critical_band FAILED [ 67%]
# tests/test_risk_scorer.py::TestComponentScores::test_income_stability_low_volatility FAILED [ 70%]
# tests/test_risk_scorer.py::TestComponentScores::test_income_stability_high_volatility PASSED [ 73%]
# tests/test_risk_scorer.py::TestComponentScores::test_debt_burden_low_dti PASSED [ 76%]
# tests/test_risk_scorer.py::TestComponentScores::test_debt_burden_critical_dti PASSED [ 79%]
# tests/test_risk_scorer.py::TestComponentScores::test_credit_score_formula PASSED [ 82%]
# tests/test_risk_scorer.py::TestComponentScores::test_emi_cushion_safe FAILED [ 85%]
# tests/test_risk_scorer.py::TestComponentScores::test_emi_cushion_critical FAILED [ 88%]
# tests/test_risk_scorer.py::TestRajeshKumarExample::test_worked_example_function PASSED [ 91%]
# tests/test_risk_scorer.py::TestBatchScoring::test_score_dataframe PASSED [ 94%]
# tests/test_risk_scorer.py::TestBatchScoring::test_score_deterministic FAILED [ 97%]
# tests/test_risk_scorer.py::TestWeights::test_weights_sum_to_one FAILED   [100%]
# 
# ================================== FAILURES ===================================
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:71: AssertionError: assert 'income_stability_index' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'isi', 'isi_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:79: AssertionError: assert 'dti_enhanced' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'computed_dti', 'dti_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:88: AssertionError: assert 'savings_rate_v2' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'savings_rate_pct', 'savings_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:94: AssertionError: assert 'emi_cushion_index' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'eci', 'eci_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:100: AssertionError: assert 'expenditure_volatility' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'evs', 'evs_ratio'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:108: AssertionError: assert 'salary_delay_trend' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'sdt', 'sdt_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:114: AssertionError: assert 'cash_deposit_pattern_score' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'cdps', 'cash_sufficiency_ratio', 'cdps_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:120: AssertionError: assert 'discretionary_spending_ratio' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'dsr', 'dsr_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:129: AssertionError: assert 'payment_timing_consistency' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'ptc', 'ptc_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:135: AssertionError: assert 'account_balance_trajectory' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'abt', 'abt_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:144: AssertionError: assert 'subscription_cascade_index' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'subscription_cascade_score'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:152: AssertionError: assert 'digital_wallet_velocity' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'wallet_velocity', 'wallet_velocity_band'],\n      dtype='object')
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:164: AssertionError: assert 'healthcare_spike_indicator' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'healthcare_current_spend', 'healthcare_spike_ratio',\n       'healthcare_spike_band'],\n      dtype='object')
# d:\loan\venv\lib\site-packages\pandas\core\indexes\base.py:3804: KeyError: 'industry_stress_index'
# D:\loan\predelinquency-engine\tests\test_feature_engineering.py:174: AssertionError: assert 'gig_income_variance' in Index(['LoanID', 'Income', 'LoanAmount', 'LoanTerm', 'CreditScore', 'DTIRatio',\n       'InterestRate', 'Default', 'segment_category', 'detailed_segment',\n       'avg_monthly_balance_6m', 'total_monthly_expense', 'expense_housing',\n       'expense_food_groceries', 'expense_transportation',\n       'expense_healthcare', 'expense_lifestyle_entertainment',\n       'expense_discretionary_vices', 'salary_delay_days', 'savings_rate',\n       'ontime_payment_rate_12m', 'payment_day_consistency',\n       'max_dpd_last_12m', 'cash_deposit_frequency_month',\n       'cash_deposit_consistency_score', 'cash_deposit_avg_amount',\n       'subscription_cascade_phase', 'p2p_borrow_requests_30d',\n       'instant_cashouts_month', 'pharmacy_expense_monthly',\n       'hospital_visits_6m', 'peer_default_rate', 'platform_daily_earning_avg',\n       'income_cv_daily', 'gig_cv_band'],\n      dtype='object')
# d:\loan\venv\lib\site-packages\pandas\core\indexes\base.py:3804: KeyError: 'industry_stress_index'
# d:\loan\venv\lib\site-packages\pandas\core\indexes\base.py:3804: KeyError: 'industry_stress_index'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:22: AssertionError: assert ('SAFE', '< 5%', 'Monitor only') == 'SAFE'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:28: AssertionError: assert ('LOW RISK', '5-15%', 'Gentle nudge, wellness tips') == 'LOW RISK'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:34: AssertionError: assert ('MODERATE', '15-35%', 'Proactive outreach, options') == 'MODERATE'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:40: AssertionError: assert ('HIGH RISK', '35-60%', 'Urgent call, restructuring') == 'HIGH RISK'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:46: AssertionError: assert ('CRITICAL', '> 60%', 'Immediate intervention') == 'CRITICAL'
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:62: assert 90 <= 30
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:93: assert 50.0 <= 30
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:99: assert 50.0 >= 60
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:139: TypeError: tuple indices must be integers or slices, not str
# D:\loan\predelinquency-engine\tests\test_risk_scorer.py:148: AssertionError: Weights sum to 1.28, expected 1.0
# =========================== short test summary info ===========================
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_income_stability_index
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_debt_to_income
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_savings_rate
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_emi_cushion_index
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_expenditure_volatility
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_salary_delay_trend
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_cash_deposit_pattern_score
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_discretionary_spending_ratio
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_payment_timing_consistency
# FAILED tests/test_feature_engineering.py::TestCoreFormulas::test_account_balance_trajectory
# FAILED tests/test_feature_engineering.py::TestAdvancedBehavioral::test_subscription_cascade
# FAILED tests/test_feature_engineering.py::TestAdvancedBehavioral::test_digital_wallet_velocity
# FAILED tests/test_feature_engineering.py::TestAdvancedBehavioral::test_healthcare_spike
# FAILED tests/test_feature_engineering.py::TestAdvancedBehavioral::test_employer_contagion
# FAILED tests/test_feature_engineering.py::TestAdvancedBehavioral::test_gig_income_variance
# FAILED tests/test_feature_engineering.py::TestFullPipeline::test_run_produces_features
# FAILED tests/test_feature_engineering.py::TestFullPipeline::test_no_all_nan_columns
# FAILED tests/test_risk_scorer.py::TestRiskBandClassification::test_safe_band
# FAILED tests/test_risk_scorer.py::TestRiskBandClassification::test_low_risk_band
# FAILED tests/test_risk_scorer.py::TestRiskBandClassification::test_moderate_band
# FAILED tests/test_risk_scorer.py::TestRiskBandClassification::test_high_risk_band
# FAILED tests/test_risk_scorer.py::TestRiskBandClassification::test_critical_band
# FAILED tests/test_risk_scorer.py::TestComponentScores::test_income_stability_low_volatility
# FAILED tests/test_risk_scorer.py::TestComponentScores::test_emi_cushion_safe
# FAILED tests/test_risk_scorer.py::TestComponentScores::test_emi_cushion_critical
# FAILED tests/test_risk_scorer.py::TestBatchScoring::test_score_deterministic
# FAILED tests/test_risk_scorer.py::TestWeights::test_weights_sum_to_one - Asse...
# ======================== 27 failed, 7 passed in 0.91s =========================
# 